/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package Practical_ServiceBuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Entity1 service. Represents a row in the &quot;Entity1_Entity1&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>Practical_ServiceBuilder.model.impl.Entity1ModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>Practical_ServiceBuilder.model.impl.Entity1Impl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Entity1
 * @generated
 */
@ProviderType
public interface Entity1Model extends BaseModel<Entity1> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a entity1 model instance should use the {@link Entity1} interface instead.
	 */

	/**
	 * Returns the primary key of this entity1.
	 *
	 * @return the primary key of this entity1
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this entity1.
	 *
	 * @param primaryKey the primary key of this entity1
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this entity1.
	 *
	 * @return the uuid of this entity1
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this entity1.
	 *
	 * @param uuid the uuid of this entity1
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the student_ ID of this entity1.
	 *
	 * @return the student_ ID of this entity1
	 */
	public long getStudent_Id();

	/**
	 * Sets the student_ ID of this entity1.
	 *
	 * @param Student_Id the student_ ID of this entity1
	 */
	public void setStudent_Id(long Student_Id);

	/**
	 * Returns the student_ name of this entity1.
	 *
	 * @return the student_ name of this entity1
	 */
	@AutoEscape
	public String getStudent_Name();

	/**
	 * Sets the student_ name of this entity1.
	 *
	 * @param Student_Name the student_ name of this entity1
	 */
	public void setStudent_Name(String Student_Name);

	/**
	 * Returns the maths_ marks of this entity1.
	 *
	 * @return the maths_ marks of this entity1
	 */
	public int getMaths_Marks();

	/**
	 * Sets the maths_ marks of this entity1.
	 *
	 * @param Maths_Marks the maths_ marks of this entity1
	 */
	public void setMaths_Marks(int Maths_Marks);

	@Override
	public Entity1 cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}