/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package Practical_ServiceBuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Entity3 service. Represents a row in the &quot;Entity1_Entity3&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>Practical_ServiceBuilder.model.impl.Entity3ModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>Practical_ServiceBuilder.model.impl.Entity3Impl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Entity3
 * @generated
 */
@ProviderType
public interface Entity3Model extends BaseModel<Entity3> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a entity3 model instance should use the {@link Entity3} interface instead.
	 */

	/**
	 * Returns the primary key of this entity3.
	 *
	 * @return the primary key of this entity3
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this entity3.
	 *
	 * @param primaryKey the primary key of this entity3
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the uuid of this entity3.
	 *
	 * @return the uuid of this entity3
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this entity3.
	 *
	 * @param uuid the uuid of this entity3
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the teacher_ ID of this entity3.
	 *
	 * @return the teacher_ ID of this entity3
	 */
	public int getTeacher_Id();

	/**
	 * Sets the teacher_ ID of this entity3.
	 *
	 * @param Teacher_Id the teacher_ ID of this entity3
	 */
	public void setTeacher_Id(int Teacher_Id);

	/**
	 * Returns the teacher_ name of this entity3.
	 *
	 * @return the teacher_ name of this entity3
	 */
	@AutoEscape
	public String getTeacher_Name();

	/**
	 * Sets the teacher_ name of this entity3.
	 *
	 * @param Teacher_Name the teacher_ name of this entity3
	 */
	public void setTeacher_Name(String Teacher_Name);

	@Override
	public Entity3 cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}