/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package Practical_ServiceBuilder.model.impl;

import Practical_ServiceBuilder.model.Entity3;
import Practical_ServiceBuilder.model.Entity3Model;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Entity3 service. Represents a row in the &quot;Entity1_Entity3&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>Entity3Model</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Entity3Impl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Entity3Impl
 * @generated
 */
public class Entity3ModelImpl
	extends BaseModelImpl<Entity3> implements Entity3Model {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a entity3 model instance should use the <code>Entity3</code> interface instead.
	 */
	public static final String TABLE_NAME = "Entity1_Entity3";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"Teacher_Id", Types.INTEGER},
		{"Teacher_Name", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Teacher_Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("Teacher_Name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Entity1_Entity3 (uuid_ VARCHAR(75) null,Teacher_Id INTEGER not null primary key,Teacher_Name VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table Entity1_Entity3";

	public static final String ORDER_BY_JPQL =
		" ORDER BY entity3.Teacher_Id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Entity1_Entity3.Teacher_Id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TEACHER_ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public Entity3ModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Teacher_Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setTeacher_Id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Teacher_Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Entity3.class;
	}

	@Override
	public String getModelClassName() {
		return Entity3.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Entity3, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Entity3, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Entity3, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Entity3)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Entity3, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Entity3, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Entity3)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Entity3, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Entity3, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Entity3, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Entity3, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Entity3, Object>>();

			attributeGetterFunctions.put("uuid", Entity3::getUuid);
			attributeGetterFunctions.put("Teacher_Id", Entity3::getTeacher_Id);
			attributeGetterFunctions.put(
				"Teacher_Name", Entity3::getTeacher_Name);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Entity3, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Entity3, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Entity3, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<Entity3, String>)Entity3::setUuid);
			attributeSetterBiConsumers.put(
				"Teacher_Id",
				(BiConsumer<Entity3, Integer>)Entity3::setTeacher_Id);
			attributeSetterBiConsumers.put(
				"Teacher_Name",
				(BiConsumer<Entity3, String>)Entity3::setTeacher_Name);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public int getTeacher_Id() {
		return _Teacher_Id;
	}

	@Override
	public void setTeacher_Id(int Teacher_Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Teacher_Id = Teacher_Id;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalTeacher_Id() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("Teacher_Id"));
	}

	@Override
	public String getTeacher_Name() {
		if (_Teacher_Name == null) {
			return "";
		}
		else {
			return _Teacher_Name;
		}
	}

	@Override
	public void setTeacher_Name(String Teacher_Name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Teacher_Name = Teacher_Name;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public Entity3 toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Entity3>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		Entity3Impl entity3Impl = new Entity3Impl();

		entity3Impl.setUuid(getUuid());
		entity3Impl.setTeacher_Id(getTeacher_Id());
		entity3Impl.setTeacher_Name(getTeacher_Name());

		entity3Impl.resetOriginalValues();

		return entity3Impl;
	}

	@Override
	public Entity3 cloneWithOriginalValues() {
		Entity3Impl entity3Impl = new Entity3Impl();

		entity3Impl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		entity3Impl.setTeacher_Id(
			this.<Integer>getColumnOriginalValue("Teacher_Id"));
		entity3Impl.setTeacher_Name(
			this.<String>getColumnOriginalValue("Teacher_Name"));

		return entity3Impl;
	}

	@Override
	public int compareTo(Entity3 entity3) {
		int value = 0;

		if (getTeacher_Id() < entity3.getTeacher_Id()) {
			value = -1;
		}
		else if (getTeacher_Id() > entity3.getTeacher_Id()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Entity3)) {
			return false;
		}

		Entity3 entity3 = (Entity3)object;

		int primaryKey = entity3.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Entity3> toCacheModel() {
		Entity3CacheModel entity3CacheModel = new Entity3CacheModel();

		entity3CacheModel.uuid = getUuid();

		String uuid = entity3CacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			entity3CacheModel.uuid = null;
		}

		entity3CacheModel.Teacher_Id = getTeacher_Id();

		entity3CacheModel.Teacher_Name = getTeacher_Name();

		String Teacher_Name = entity3CacheModel.Teacher_Name;

		if ((Teacher_Name != null) && (Teacher_Name.length() == 0)) {
			entity3CacheModel.Teacher_Name = null;
		}

		return entity3CacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Entity3, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Entity3, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Entity3, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Entity3)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Entity3>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Entity3.class, ModelWrapper.class);

	}

	private String _uuid;
	private int _Teacher_Id;
	private String _Teacher_Name;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Entity3, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Entity3)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("Teacher_Id", _Teacher_Id);
		_columnOriginalValues.put("Teacher_Name", _Teacher_Name);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("Teacher_Id", 2L);

		columnBitmasks.put("Teacher_Name", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Entity3 _escapedModel;

}