/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package Practical_ServiceBuilder.model.impl;

import Practical_ServiceBuilder.model.Entity1;
import Practical_ServiceBuilder.model.Entity1Model;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Entity1 service. Represents a row in the &quot;Entity1_Entity1&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>Entity1Model</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Entity1Impl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Entity1Impl
 * @generated
 */
public class Entity1ModelImpl
	extends BaseModelImpl<Entity1> implements Entity1Model {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a entity1 model instance should use the <code>Entity1</code> interface instead.
	 */
	public static final String TABLE_NAME = "Entity1_Entity1";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"Student_Id", Types.BIGINT},
		{"Student_Name", Types.VARCHAR}, {"Maths_Marks", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Student_Id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("Student_Name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Maths_Marks", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Entity1_Entity1 (uuid_ VARCHAR(75) null,Student_Id LONG not null primary key,Student_Name VARCHAR(75) null,Maths_Marks INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table Entity1_Entity1";

	public static final String ORDER_BY_JPQL =
		" ORDER BY entity1.Student_Name ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Entity1_Entity1.Student_Name ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STUDENT_NAME_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public Entity1ModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _Student_Id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setStudent_Id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Student_Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Entity1.class;
	}

	@Override
	public String getModelClassName() {
		return Entity1.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Entity1, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Entity1, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Entity1, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Entity1)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Entity1, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Entity1, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Entity1)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Entity1, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Entity1, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Entity1, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Entity1, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Entity1, Object>>();

			attributeGetterFunctions.put("uuid", Entity1::getUuid);
			attributeGetterFunctions.put("Student_Id", Entity1::getStudent_Id);
			attributeGetterFunctions.put(
				"Student_Name", Entity1::getStudent_Name);
			attributeGetterFunctions.put(
				"Maths_Marks", Entity1::getMaths_Marks);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Entity1, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Entity1, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Entity1, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<Entity1, String>)Entity1::setUuid);
			attributeSetterBiConsumers.put(
				"Student_Id",
				(BiConsumer<Entity1, Long>)Entity1::setStudent_Id);
			attributeSetterBiConsumers.put(
				"Student_Name",
				(BiConsumer<Entity1, String>)Entity1::setStudent_Name);
			attributeSetterBiConsumers.put(
				"Maths_Marks",
				(BiConsumer<Entity1, Integer>)Entity1::setMaths_Marks);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getStudent_Id() {
		return _Student_Id;
	}

	@Override
	public void setStudent_Id(long Student_Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Student_Id = Student_Id;
	}

	@Override
	public String getStudent_Name() {
		if (_Student_Name == null) {
			return "";
		}
		else {
			return _Student_Name;
		}
	}

	@Override
	public void setStudent_Name(String Student_Name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Student_Name = Student_Name;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalStudent_Name() {
		return getColumnOriginalValue("Student_Name");
	}

	@Override
	public int getMaths_Marks() {
		return _Maths_Marks;
	}

	@Override
	public void setMaths_Marks(int Maths_Marks) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Maths_Marks = Maths_Marks;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Entity1.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Entity1 toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Entity1>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		Entity1Impl entity1Impl = new Entity1Impl();

		entity1Impl.setUuid(getUuid());
		entity1Impl.setStudent_Id(getStudent_Id());
		entity1Impl.setStudent_Name(getStudent_Name());
		entity1Impl.setMaths_Marks(getMaths_Marks());

		entity1Impl.resetOriginalValues();

		return entity1Impl;
	}

	@Override
	public Entity1 cloneWithOriginalValues() {
		Entity1Impl entity1Impl = new Entity1Impl();

		entity1Impl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		entity1Impl.setStudent_Id(
			this.<Long>getColumnOriginalValue("Student_Id"));
		entity1Impl.setStudent_Name(
			this.<String>getColumnOriginalValue("Student_Name"));
		entity1Impl.setMaths_Marks(
			this.<Integer>getColumnOriginalValue("Maths_Marks"));

		return entity1Impl;
	}

	@Override
	public int compareTo(Entity1 entity1) {
		int value = 0;

		value = getStudent_Name().compareTo(entity1.getStudent_Name());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Entity1)) {
			return false;
		}

		Entity1 entity1 = (Entity1)object;

		long primaryKey = entity1.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Entity1> toCacheModel() {
		Entity1CacheModel entity1CacheModel = new Entity1CacheModel();

		entity1CacheModel.uuid = getUuid();

		String uuid = entity1CacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			entity1CacheModel.uuid = null;
		}

		entity1CacheModel.Student_Id = getStudent_Id();

		entity1CacheModel.Student_Name = getStudent_Name();

		String Student_Name = entity1CacheModel.Student_Name;

		if ((Student_Name != null) && (Student_Name.length() == 0)) {
			entity1CacheModel.Student_Name = null;
		}

		entity1CacheModel.Maths_Marks = getMaths_Marks();

		return entity1CacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Entity1, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Entity1, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Entity1, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Entity1)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Entity1>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Entity1.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _Student_Id;
	private String _Student_Name;
	private int _Maths_Marks;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Entity1, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Entity1)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("Student_Id", _Student_Id);
		_columnOriginalValues.put("Student_Name", _Student_Name);
		_columnOriginalValues.put("Maths_Marks", _Maths_Marks);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("Student_Id", 2L);

		columnBitmasks.put("Student_Name", 4L);

		columnBitmasks.put("Maths_Marks", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Entity1 _escapedModel;

}