/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package Practical_ServiceBuilder.model.impl;

import Practical_ServiceBuilder.model.Entity2;

import Practical_ServiceBuilder.service.Entity2LocalServiceUtil;

/**
 * The extended model base implementation for the Entity2 service. Represents a row in the &quot;Entity1_Entity2&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Entity2Impl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Entity2Impl
 * @see Entity2
 * @generated
 */
public abstract class Entity2BaseImpl
	extends Entity2ModelImpl implements Entity2 {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a entity2 model instance should use the <code>Entity2</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			Entity2LocalServiceUtil.addEntity2(this);
		}
		else {
			Entity2LocalServiceUtil.updateEntity2(this);
		}
	}

}