/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package Practical_ServiceBuilder.model.impl;

import Practical_ServiceBuilder.model.Entity4;

import Practical_ServiceBuilder.service.Entity4LocalServiceUtil;

/**
 * The extended model base implementation for the Entity4 service. Represents a row in the &quot;Entity1_Entity4&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Entity4Impl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Entity4Impl
 * @see Entity4
 * @generated
 */
public abstract class Entity4BaseImpl
	extends Entity4ModelImpl implements Entity4 {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a entity4 model instance should use the <code>Entity4</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			Entity4LocalServiceUtil.addEntity4(this);
		}
		else {
			Entity4LocalServiceUtil.updateEntity4(this);
		}
	}

}