info:
    description: "StudentobjectHttpOptions REST API"
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "StudentobjectHttpOptions"
    version: v1.0
openapi: 3.0.1

components:
  schemas:
    StudentsObject:
      properties:
        studentId:
          type: integer
          format: int32
        studentName:
          type: string
        departmentId:
          type: integer
          format: int32


paths:
  /create-student:
    post:
      operationId: createStudentObject
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StudentsObject"
          application/xml:
            schema:
              $ref: "#/components/schemas/StudentsObject"
      responses:
        200:
          description: "Success Response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StudentsObject"
            application/xml:
              schema:
                $ref: "#/components/schemas/StudentsObject"
      tags: ["StudentsObject"]
      
  
  /students:
    get:
      operationId: getStudentObjects
      responses:
        200:
          description: "Success Response"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/StudentsObject"
            application/xml:
              schema:
                items:
                  $ref: "#/components/schemas/StudentsObject"
      tags: ["StudentsObject"]
      
  /update-student:
    post:
      operationId: updateStudent
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StudentsObject"
          application/xml:
            schema:
              $ref: "#/components/schemas/StudentsObject"
      responses:
        200:
          description: "Success Response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StudentsObject"
            application/xml:
              schema:
                $ref: "#/components/schemas/StudentsObject"
      tags: ["StudentsObject"]
      
      
  /delete/{studentId}:
    get:
      operationId: deleteStudentObject
      parameters:
        - in: path
          name: studentId
          required: true
          schema:
            type: integer
            format: int32
      responses:
        200:
          description: "Success Response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StudentsObject"
            application/xml:
              schema:
                $ref: "#/components/schemas/StudentsObject"
      tags: ["StudentsObject"]



