/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.Students.Details.model.impl;

import com.Students.Details.model.Department_Details;
import com.Students.Details.model.Department_DetailsModel;

import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Department_Details service. Represents a row in the &quot;Department_Details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>Department_DetailsModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Department_DetailsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Department_DetailsImpl
 * @generated
 */
public class Department_DetailsModelImpl
	extends BaseModelImpl<Department_Details>
	implements Department_DetailsModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a department_ details model instance should use the <code>Department_Details</code> interface instead.
	 */
	public static final String TABLE_NAME = "Department_Details";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"Department_Id", Types.INTEGER},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"Department_Name", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Department_Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("Department_Name", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Department_Details (uuid_ VARCHAR(75) null,Department_Id INTEGER not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,Department_Name VARCHAR(250) null)";

	public static final String TABLE_SQL_DROP = "drop table Department_Details";

	public static final String ORDER_BY_JPQL =
		" ORDER BY department_Details.Department_Id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Department_Details.Department_Id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DEPARTMENT_ID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public Department_DetailsModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Department_Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setDepartment_Id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Department_Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Department_Details.class;
	}

	@Override
	public String getModelClassName() {
		return Department_Details.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Department_Details, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Department_Details, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Department_Details, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((Department_Details)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Department_Details, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Department_Details, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Department_Details)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Department_Details, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Department_Details, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Department_Details, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Department_Details, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<Department_Details, Object>>();

			attributeGetterFunctions.put("uuid", Department_Details::getUuid);
			attributeGetterFunctions.put(
				"Department_Id", Department_Details::getDepartment_Id);
			attributeGetterFunctions.put(
				"groupId", Department_Details::getGroupId);
			attributeGetterFunctions.put(
				"companyId", Department_Details::getCompanyId);
			attributeGetterFunctions.put(
				"userId", Department_Details::getUserId);
			attributeGetterFunctions.put(
				"userName", Department_Details::getUserName);
			attributeGetterFunctions.put(
				"createDate", Department_Details::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Department_Details::getModifiedDate);
			attributeGetterFunctions.put(
				"Department_Name", Department_Details::getDepartment_Name);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Department_Details, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Department_Details, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<Department_Details, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<Department_Details, String>)
					Department_Details::setUuid);
			attributeSetterBiConsumers.put(
				"Department_Id",
				(BiConsumer<Department_Details, Integer>)
					Department_Details::setDepartment_Id);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<Department_Details, Long>)
					Department_Details::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<Department_Details, Long>)
					Department_Details::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<Department_Details, Long>)
					Department_Details::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<Department_Details, String>)
					Department_Details::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<Department_Details, Date>)
					Department_Details::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Department_Details, Date>)
					Department_Details::setModifiedDate);
			attributeSetterBiConsumers.put(
				"Department_Name",
				(BiConsumer<Department_Details, String>)
					Department_Details::setDepartment_Name);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public int getDepartment_Id() {
		return _Department_Id;
	}

	@Override
	public void setDepartment_Id(int Department_Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Department_Id = Department_Id;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getDepartment_Name() {
		if (_Department_Name == null) {
			return "";
		}
		else {
			return _Department_Name;
		}
	}

	@Override
	public void setDepartment_Name(String Department_Name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Department_Name = Department_Name;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Department_Details.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public Department_Details toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Department_Details>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		Department_DetailsImpl department_DetailsImpl =
			new Department_DetailsImpl();

		department_DetailsImpl.setUuid(getUuid());
		department_DetailsImpl.setDepartment_Id(getDepartment_Id());
		department_DetailsImpl.setGroupId(getGroupId());
		department_DetailsImpl.setCompanyId(getCompanyId());
		department_DetailsImpl.setUserId(getUserId());
		department_DetailsImpl.setUserName(getUserName());
		department_DetailsImpl.setCreateDate(getCreateDate());
		department_DetailsImpl.setModifiedDate(getModifiedDate());
		department_DetailsImpl.setDepartment_Name(getDepartment_Name());

		department_DetailsImpl.resetOriginalValues();

		return department_DetailsImpl;
	}

	@Override
	public Department_Details cloneWithOriginalValues() {
		Department_DetailsImpl department_DetailsImpl =
			new Department_DetailsImpl();

		department_DetailsImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		department_DetailsImpl.setDepartment_Id(
			this.<Integer>getColumnOriginalValue("Department_Id"));
		department_DetailsImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		department_DetailsImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		department_DetailsImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		department_DetailsImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		department_DetailsImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		department_DetailsImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		department_DetailsImpl.setDepartment_Name(
			this.<String>getColumnOriginalValue("Department_Name"));

		return department_DetailsImpl;
	}

	@Override
	public int compareTo(Department_Details department_Details) {
		int primaryKey = department_Details.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Department_Details)) {
			return false;
		}

		Department_Details department_Details = (Department_Details)object;

		int primaryKey = department_Details.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Department_Details> toCacheModel() {
		Department_DetailsCacheModel department_DetailsCacheModel =
			new Department_DetailsCacheModel();

		department_DetailsCacheModel.uuid = getUuid();

		String uuid = department_DetailsCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			department_DetailsCacheModel.uuid = null;
		}

		department_DetailsCacheModel.Department_Id = getDepartment_Id();

		department_DetailsCacheModel.groupId = getGroupId();

		department_DetailsCacheModel.companyId = getCompanyId();

		department_DetailsCacheModel.userId = getUserId();

		department_DetailsCacheModel.userName = getUserName();

		String userName = department_DetailsCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			department_DetailsCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			department_DetailsCacheModel.createDate = createDate.getTime();
		}
		else {
			department_DetailsCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			department_DetailsCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			department_DetailsCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		department_DetailsCacheModel.Department_Name = getDepartment_Name();

		String Department_Name = department_DetailsCacheModel.Department_Name;

		if ((Department_Name != null) && (Department_Name.length() == 0)) {
			department_DetailsCacheModel.Department_Name = null;
		}

		return department_DetailsCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Department_Details, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Department_Details, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Department_Details, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(Department_Details)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Department_Details>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Department_Details.class, ModelWrapper.class);

	}

	private String _uuid;
	private int _Department_Id;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _Department_Name;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Department_Details, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Department_Details)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("Department_Id", _Department_Id);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("Department_Name", _Department_Name);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("Department_Id", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("Department_Name", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Department_Details _escapedModel;

}