/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.Students.Details.model.impl;

import com.Students.Details.model.Students_Marks;
import com.Students.Details.service.Students_MarksLocalServiceUtil;

/**
 * The extended model base implementation for the Students_Marks service. Represents a row in the &quot;Students_Marks&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Students_MarksImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Students_MarksImpl
 * @see Students_Marks
 * @generated
 */
public abstract class Students_MarksBaseImpl
	extends Students_MarksModelImpl implements Students_Marks {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a students_ marks model instance should use the <code>Students_Marks</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			Students_MarksLocalServiceUtil.addStudents_Marks(this);
		}
		else {
			Students_MarksLocalServiceUtil.updateStudents_Marks(this);
		}
	}

}