/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.Students.Details.model.impl;

import com.Students.Details.model.Students_Marks;
import com.Students.Details.model.Students_MarksModel;

import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Students_Marks service. Represents a row in the &quot;Students_Marks&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>Students_MarksModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Students_MarksImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Students_MarksImpl
 * @generated
 */
public class Students_MarksModelImpl
	extends BaseModelImpl<Students_Marks> implements Students_MarksModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a students_ marks model instance should use the <code>Students_Marks</code> interface instead.
	 */
	public static final String TABLE_NAME = "Students_Marks";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"Student_Id", Types.INTEGER},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"Student_Marks", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Student_Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("Student_Marks", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Students_Marks (uuid_ VARCHAR(75) null,Student_Id INTEGER not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,Student_Marks VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table Students_Marks";

	public static final String ORDER_BY_JPQL =
		" ORDER BY students_Marks.Student_Id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Students_Marks.Student_Id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STUDENT_ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public Students_MarksModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Student_Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setStudent_Id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Student_Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Students_Marks.class;
	}

	@Override
	public String getModelClassName() {
		return Students_Marks.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Students_Marks, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Students_Marks, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Students_Marks, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((Students_Marks)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Students_Marks, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Students_Marks, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Students_Marks)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Students_Marks, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Students_Marks, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Students_Marks, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Students_Marks, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<Students_Marks, Object>>();

			attributeGetterFunctions.put("uuid", Students_Marks::getUuid);
			attributeGetterFunctions.put(
				"Student_Id", Students_Marks::getStudent_Id);
			attributeGetterFunctions.put("groupId", Students_Marks::getGroupId);
			attributeGetterFunctions.put(
				"companyId", Students_Marks::getCompanyId);
			attributeGetterFunctions.put("userId", Students_Marks::getUserId);
			attributeGetterFunctions.put(
				"userName", Students_Marks::getUserName);
			attributeGetterFunctions.put(
				"createDate", Students_Marks::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Students_Marks::getModifiedDate);
			attributeGetterFunctions.put(
				"Student_Marks", Students_Marks::getStudent_Marks);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Students_Marks, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Students_Marks, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<Students_Marks, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<Students_Marks, String>)Students_Marks::setUuid);
			attributeSetterBiConsumers.put(
				"Student_Id",
				(BiConsumer<Students_Marks, Integer>)
					Students_Marks::setStudent_Id);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<Students_Marks, Long>)Students_Marks::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<Students_Marks, Long>)Students_Marks::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<Students_Marks, Long>)Students_Marks::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<Students_Marks, String>)
					Students_Marks::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<Students_Marks, Date>)
					Students_Marks::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Students_Marks, Date>)
					Students_Marks::setModifiedDate);
			attributeSetterBiConsumers.put(
				"Student_Marks",
				(BiConsumer<Students_Marks, String>)
					Students_Marks::setStudent_Marks);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public int getStudent_Id() {
		return _Student_Id;
	}

	@Override
	public void setStudent_Id(int Student_Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Student_Id = Student_Id;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalStudent_Id() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("Student_Id"));
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getStudent_Marks() {
		if (_Student_Marks == null) {
			return "";
		}
		else {
			return _Student_Marks;
		}
	}

	@Override
	public void setStudent_Marks(String Student_Marks) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Student_Marks = Student_Marks;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Students_Marks.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public Students_Marks toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Students_Marks>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		Students_MarksImpl students_MarksImpl = new Students_MarksImpl();

		students_MarksImpl.setUuid(getUuid());
		students_MarksImpl.setStudent_Id(getStudent_Id());
		students_MarksImpl.setGroupId(getGroupId());
		students_MarksImpl.setCompanyId(getCompanyId());
		students_MarksImpl.setUserId(getUserId());
		students_MarksImpl.setUserName(getUserName());
		students_MarksImpl.setCreateDate(getCreateDate());
		students_MarksImpl.setModifiedDate(getModifiedDate());
		students_MarksImpl.setStudent_Marks(getStudent_Marks());

		students_MarksImpl.resetOriginalValues();

		return students_MarksImpl;
	}

	@Override
	public Students_Marks cloneWithOriginalValues() {
		Students_MarksImpl students_MarksImpl = new Students_MarksImpl();

		students_MarksImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		students_MarksImpl.setStudent_Id(
			this.<Integer>getColumnOriginalValue("Student_Id"));
		students_MarksImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		students_MarksImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		students_MarksImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		students_MarksImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		students_MarksImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		students_MarksImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		students_MarksImpl.setStudent_Marks(
			this.<String>getColumnOriginalValue("Student_Marks"));

		return students_MarksImpl;
	}

	@Override
	public int compareTo(Students_Marks students_Marks) {
		int primaryKey = students_Marks.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Students_Marks)) {
			return false;
		}

		Students_Marks students_Marks = (Students_Marks)object;

		int primaryKey = students_Marks.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Students_Marks> toCacheModel() {
		Students_MarksCacheModel students_MarksCacheModel =
			new Students_MarksCacheModel();

		students_MarksCacheModel.uuid = getUuid();

		String uuid = students_MarksCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			students_MarksCacheModel.uuid = null;
		}

		students_MarksCacheModel.Student_Id = getStudent_Id();

		students_MarksCacheModel.groupId = getGroupId();

		students_MarksCacheModel.companyId = getCompanyId();

		students_MarksCacheModel.userId = getUserId();

		students_MarksCacheModel.userName = getUserName();

		String userName = students_MarksCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			students_MarksCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			students_MarksCacheModel.createDate = createDate.getTime();
		}
		else {
			students_MarksCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			students_MarksCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			students_MarksCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		students_MarksCacheModel.Student_Marks = getStudent_Marks();

		String Student_Marks = students_MarksCacheModel.Student_Marks;

		if ((Student_Marks != null) && (Student_Marks.length() == 0)) {
			students_MarksCacheModel.Student_Marks = null;
		}

		return students_MarksCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Students_Marks, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Students_Marks, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Students_Marks, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Students_Marks)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Students_Marks>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Students_Marks.class, ModelWrapper.class);

	}

	private String _uuid;
	private int _Student_Id;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _Student_Marks;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Students_Marks, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Students_Marks)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("Student_Id", _Student_Id);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("Student_Marks", _Student_Marks);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("Student_Id", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("Student_Marks", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Students_Marks _escapedModel;

}