/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.Students.Details.model.impl;

import com.Students.Details.model.TeacherDetails;
import com.Students.Details.service.TeacherDetailsLocalServiceUtil;

/**
 * The extended model base implementation for the TeacherDetails service. Represents a row in the &quot;Teacher_Details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TeacherDetailsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TeacherDetailsImpl
 * @see TeacherDetails
 * @generated
 */
public abstract class TeacherDetailsBaseImpl
	extends TeacherDetailsModelImpl implements TeacherDetails {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a teacher details model instance should use the <code>TeacherDetails</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			TeacherDetailsLocalServiceUtil.addTeacherDetails(this);
		}
		else {
			TeacherDetailsLocalServiceUtil.updateTeacherDetails(this);
		}
	}

}