/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.Students.Details.model.impl;

import com.Students.Details.model.TeacherDetails;
import com.Students.Details.model.TeacherDetailsModel;

import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TeacherDetails service. Represents a row in the &quot;Teacher_Details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TeacherDetailsModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TeacherDetailsImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TeacherDetailsImpl
 * @generated
 */
public class TeacherDetailsModelImpl
	extends BaseModelImpl<TeacherDetails> implements TeacherDetailsModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a teacher details model instance should use the <code>TeacherDetails</code> interface instead.
	 */
	public static final String TABLE_NAME = "Teacher_Details";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"Teacher_Id", Types.INTEGER},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"Teacher_Name", Types.VARCHAR}, {"Department_Id", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Teacher_Id", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("Teacher_Name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Department_Id", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Teacher_Details (uuid_ VARCHAR(75) null,Teacher_Id INTEGER not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,Teacher_Name VARCHAR(75) null,Department_Id INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table Teacher_Details";

	public static final String ORDER_BY_JPQL =
		" ORDER BY teacherDetails.Teacher_Id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Teacher_Details.Teacher_Id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DEPARTMENT_ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TEACHER_ID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public TeacherDetailsModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _Teacher_Id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setTeacher_Id(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Teacher_Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TeacherDetails.class;
	}

	@Override
	public String getModelClassName() {
		return TeacherDetails.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TeacherDetails, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TeacherDetails, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TeacherDetails, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((TeacherDetails)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TeacherDetails, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TeacherDetails, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TeacherDetails)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TeacherDetails, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TeacherDetails, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<TeacherDetails, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<TeacherDetails, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<TeacherDetails, Object>>();

			attributeGetterFunctions.put("uuid", TeacherDetails::getUuid);
			attributeGetterFunctions.put(
				"Teacher_Id", TeacherDetails::getTeacher_Id);
			attributeGetterFunctions.put("groupId", TeacherDetails::getGroupId);
			attributeGetterFunctions.put(
				"companyId", TeacherDetails::getCompanyId);
			attributeGetterFunctions.put("userId", TeacherDetails::getUserId);
			attributeGetterFunctions.put(
				"userName", TeacherDetails::getUserName);
			attributeGetterFunctions.put(
				"createDate", TeacherDetails::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", TeacherDetails::getModifiedDate);
			attributeGetterFunctions.put(
				"Teacher_Name", TeacherDetails::getTeacher_Name);
			attributeGetterFunctions.put(
				"Department_Id", TeacherDetails::getDepartment_Id);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<TeacherDetails, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<TeacherDetails, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<TeacherDetails, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<TeacherDetails, String>)TeacherDetails::setUuid);
			attributeSetterBiConsumers.put(
				"Teacher_Id",
				(BiConsumer<TeacherDetails, Integer>)
					TeacherDetails::setTeacher_Id);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<TeacherDetails, Long>)TeacherDetails::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<TeacherDetails, Long>)TeacherDetails::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<TeacherDetails, Long>)TeacherDetails::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<TeacherDetails, String>)
					TeacherDetails::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<TeacherDetails, Date>)
					TeacherDetails::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<TeacherDetails, Date>)
					TeacherDetails::setModifiedDate);
			attributeSetterBiConsumers.put(
				"Teacher_Name",
				(BiConsumer<TeacherDetails, String>)
					TeacherDetails::setTeacher_Name);
			attributeSetterBiConsumers.put(
				"Department_Id",
				(BiConsumer<TeacherDetails, Integer>)
					TeacherDetails::setDepartment_Id);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public int getTeacher_Id() {
		return _Teacher_Id;
	}

	@Override
	public void setTeacher_Id(int Teacher_Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Teacher_Id = Teacher_Id;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getTeacher_Name() {
		if (_Teacher_Name == null) {
			return "";
		}
		else {
			return _Teacher_Name;
		}
	}

	@Override
	public void setTeacher_Name(String Teacher_Name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Teacher_Name = Teacher_Name;
	}

	@Override
	public int getDepartment_Id() {
		return _Department_Id;
	}

	@Override
	public void setDepartment_Id(int Department_Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Department_Id = Department_Id;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalDepartment_Id() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("Department_Id"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(TeacherDetails.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public TeacherDetails toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TeacherDetails>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TeacherDetailsImpl teacherDetailsImpl = new TeacherDetailsImpl();

		teacherDetailsImpl.setUuid(getUuid());
		teacherDetailsImpl.setTeacher_Id(getTeacher_Id());
		teacherDetailsImpl.setGroupId(getGroupId());
		teacherDetailsImpl.setCompanyId(getCompanyId());
		teacherDetailsImpl.setUserId(getUserId());
		teacherDetailsImpl.setUserName(getUserName());
		teacherDetailsImpl.setCreateDate(getCreateDate());
		teacherDetailsImpl.setModifiedDate(getModifiedDate());
		teacherDetailsImpl.setTeacher_Name(getTeacher_Name());
		teacherDetailsImpl.setDepartment_Id(getDepartment_Id());

		teacherDetailsImpl.resetOriginalValues();

		return teacherDetailsImpl;
	}

	@Override
	public TeacherDetails cloneWithOriginalValues() {
		TeacherDetailsImpl teacherDetailsImpl = new TeacherDetailsImpl();

		teacherDetailsImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		teacherDetailsImpl.setTeacher_Id(
			this.<Integer>getColumnOriginalValue("Teacher_Id"));
		teacherDetailsImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		teacherDetailsImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		teacherDetailsImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		teacherDetailsImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		teacherDetailsImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		teacherDetailsImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		teacherDetailsImpl.setTeacher_Name(
			this.<String>getColumnOriginalValue("Teacher_Name"));
		teacherDetailsImpl.setDepartment_Id(
			this.<Integer>getColumnOriginalValue("Department_Id"));

		return teacherDetailsImpl;
	}

	@Override
	public int compareTo(TeacherDetails teacherDetails) {
		int primaryKey = teacherDetails.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof TeacherDetails)) {
			return false;
		}

		TeacherDetails teacherDetails = (TeacherDetails)object;

		int primaryKey = teacherDetails.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<TeacherDetails> toCacheModel() {
		TeacherDetailsCacheModel teacherDetailsCacheModel =
			new TeacherDetailsCacheModel();

		teacherDetailsCacheModel.uuid = getUuid();

		String uuid = teacherDetailsCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			teacherDetailsCacheModel.uuid = null;
		}

		teacherDetailsCacheModel.Teacher_Id = getTeacher_Id();

		teacherDetailsCacheModel.groupId = getGroupId();

		teacherDetailsCacheModel.companyId = getCompanyId();

		teacherDetailsCacheModel.userId = getUserId();

		teacherDetailsCacheModel.userName = getUserName();

		String userName = teacherDetailsCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			teacherDetailsCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			teacherDetailsCacheModel.createDate = createDate.getTime();
		}
		else {
			teacherDetailsCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			teacherDetailsCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			teacherDetailsCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		teacherDetailsCacheModel.Teacher_Name = getTeacher_Name();

		String Teacher_Name = teacherDetailsCacheModel.Teacher_Name;

		if ((Teacher_Name != null) && (Teacher_Name.length() == 0)) {
			teacherDetailsCacheModel.Teacher_Name = null;
		}

		teacherDetailsCacheModel.Department_Id = getDepartment_Id();

		return teacherDetailsCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TeacherDetails, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TeacherDetails, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TeacherDetails, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((TeacherDetails)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, TeacherDetails>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					TeacherDetails.class, ModelWrapper.class);

	}

	private String _uuid;
	private int _Teacher_Id;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _Teacher_Name;
	private int _Department_Id;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<TeacherDetails, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((TeacherDetails)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("Teacher_Id", _Teacher_Id);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("Teacher_Name", _Teacher_Name);
		_columnOriginalValues.put("Department_Id", _Department_Id);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("Teacher_Id", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("Teacher_Name", 256L);

		columnBitmasks.put("Department_Id", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private TeacherDetails _escapedModel;

}