/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.Students.Details.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Students_Marks service. Represents a row in the &quot;Students_Marks&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.Students.Details.model.impl.Students_MarksModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.Students.Details.model.impl.Students_MarksImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Students_Marks
 * @generated
 */
@ProviderType
public interface Students_MarksModel
	extends BaseModel<Students_Marks>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a students_ marks model instance should use the {@link Students_Marks} interface instead.
	 */

	/**
	 * Returns the primary key of this students_ marks.
	 *
	 * @return the primary key of this students_ marks
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this students_ marks.
	 *
	 * @param primaryKey the primary key of this students_ marks
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the uuid of this students_ marks.
	 *
	 * @return the uuid of this students_ marks
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this students_ marks.
	 *
	 * @param uuid the uuid of this students_ marks
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the student_ ID of this students_ marks.
	 *
	 * @return the student_ ID of this students_ marks
	 */
	public int getStudent_Id();

	/**
	 * Sets the student_ ID of this students_ marks.
	 *
	 * @param Student_Id the student_ ID of this students_ marks
	 */
	public void setStudent_Id(int Student_Id);

	/**
	 * Returns the group ID of this students_ marks.
	 *
	 * @return the group ID of this students_ marks
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this students_ marks.
	 *
	 * @param groupId the group ID of this students_ marks
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this students_ marks.
	 *
	 * @return the company ID of this students_ marks
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this students_ marks.
	 *
	 * @param companyId the company ID of this students_ marks
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this students_ marks.
	 *
	 * @return the user ID of this students_ marks
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this students_ marks.
	 *
	 * @param userId the user ID of this students_ marks
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this students_ marks.
	 *
	 * @return the user uuid of this students_ marks
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this students_ marks.
	 *
	 * @param userUuid the user uuid of this students_ marks
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this students_ marks.
	 *
	 * @return the user name of this students_ marks
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this students_ marks.
	 *
	 * @param userName the user name of this students_ marks
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this students_ marks.
	 *
	 * @return the create date of this students_ marks
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this students_ marks.
	 *
	 * @param createDate the create date of this students_ marks
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this students_ marks.
	 *
	 * @return the modified date of this students_ marks
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this students_ marks.
	 *
	 * @param modifiedDate the modified date of this students_ marks
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the student_ marks of this students_ marks.
	 *
	 * @return the student_ marks of this students_ marks
	 */
	@AutoEscape
	public String getStudent_Marks();

	/**
	 * Sets the student_ marks of this students_ marks.
	 *
	 * @param Student_Marks the student_ marks of this students_ marks
	 */
	public void setStudent_Marks(String Student_Marks);

	@Override
	public Students_Marks cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}