/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.Students.Details.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TeacherDetails service. Represents a row in the &quot;Teacher_Details&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.Students.Details.model.impl.TeacherDetailsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.Students.Details.model.impl.TeacherDetailsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TeacherDetails
 * @generated
 */
@ProviderType
public interface TeacherDetailsModel
	extends BaseModel<TeacherDetails>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a teacher details model instance should use the {@link TeacherDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this teacher details.
	 *
	 * @return the primary key of this teacher details
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this teacher details.
	 *
	 * @param primaryKey the primary key of this teacher details
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the uuid of this teacher details.
	 *
	 * @return the uuid of this teacher details
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this teacher details.
	 *
	 * @param uuid the uuid of this teacher details
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the teacher_ ID of this teacher details.
	 *
	 * @return the teacher_ ID of this teacher details
	 */
	public int getTeacher_Id();

	/**
	 * Sets the teacher_ ID of this teacher details.
	 *
	 * @param Teacher_Id the teacher_ ID of this teacher details
	 */
	public void setTeacher_Id(int Teacher_Id);

	/**
	 * Returns the group ID of this teacher details.
	 *
	 * @return the group ID of this teacher details
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this teacher details.
	 *
	 * @param groupId the group ID of this teacher details
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this teacher details.
	 *
	 * @return the company ID of this teacher details
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this teacher details.
	 *
	 * @param companyId the company ID of this teacher details
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this teacher details.
	 *
	 * @return the user ID of this teacher details
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this teacher details.
	 *
	 * @param userId the user ID of this teacher details
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this teacher details.
	 *
	 * @return the user uuid of this teacher details
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this teacher details.
	 *
	 * @param userUuid the user uuid of this teacher details
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this teacher details.
	 *
	 * @return the user name of this teacher details
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this teacher details.
	 *
	 * @param userName the user name of this teacher details
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this teacher details.
	 *
	 * @return the create date of this teacher details
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this teacher details.
	 *
	 * @param createDate the create date of this teacher details
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this teacher details.
	 *
	 * @return the modified date of this teacher details
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this teacher details.
	 *
	 * @param modifiedDate the modified date of this teacher details
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the teacher_ name of this teacher details.
	 *
	 * @return the teacher_ name of this teacher details
	 */
	@AutoEscape
	public String getTeacher_Name();

	/**
	 * Sets the teacher_ name of this teacher details.
	 *
	 * @param Teacher_Name the teacher_ name of this teacher details
	 */
	public void setTeacher_Name(String Teacher_Name);

	/**
	 * Returns the department_ ID of this teacher details.
	 *
	 * @return the department_ ID of this teacher details
	 */
	public int getDepartment_Id();

	/**
	 * Sets the department_ ID of this teacher details.
	 *
	 * @param Department_Id the department_ ID of this teacher details
	 */
	public void setDepartment_Id(int Department_Id);

	@Override
	public TeacherDetails cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}